In [1]:
import numpy
n=numpy.arange(27)

In [2]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
import cv2

In [6]:
im_g=cv2.imread("smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [8]:
cv2.imwrite("newsmallgray.png",im_g)


True

In [9]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [10]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [20]:
for i in im_g:
   print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [21]:
for i in im_g.flat:
   print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [22]:
ims=numpy.hstack((im_g,im_g))

In [24]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [25]:
Ist=numpy.hsplit(ims,5)

In [26]:
Ist

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8),
 array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8),
 array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8),
 array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8),
 array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [34]:
Ist=numpy.vsplit(ims,3)

In [35]:
Ist

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]